### ISSUE TITLE
An interactive NFT gallery

### ISSUE THREAD

**Issue by DitlevHB** [sporeproject/spore-frontend#46]
I was thinking it would be interesting with an interactive gallery on the new website made in Unity where you can browse all the live NFT's in a mushroomy cave or something; this obviously needs to be developed further. I can personally start the development in a new repo and others could join in if interested.

Let me know what you think!

**Comment by florez-alberto** [comment]
You are welcome to fork the repo and work on an improved version of the NFT gallery, then do a PR and it there is no conflicts we can merge it

**Comment by florez-alberto** [comment]
closing this issue. We will be improving the UI soon.
