### ISSUE TITLE
NPM packages inconsistency

### ISSUE THREAD

**Issue by tonygustafsson** [sporeproject/spore-frontend#93]
```npm install``` doesn't work because react-lottie requires react 16 tops, and the project is using react 17. Lottie is working on their version 3, but until then it doesn't seem possible to make it work other than the ```--force``` flag which is not ideal.

**Comment by florez-alberto** [comment]
The Lottie requirements just give a warning during npm install, and the code passes vercel checks so there is nothing to change.

**Comment by florez-alberto** [comment]
react-lottie has been eliminated in our latest version
