### ISSUE TITLE
Formatting and linting

### ISSUE THREAD

**Issue by tonygustafsson** [sporeproject/spore-frontend#94]
You lack both formatting tools and linting to keep consistency. Sometimes you use single quotes, sometimes double. Sometime you end lines with semi colon, sometimes you don't.

I would recommend adding prettier for formatting and eslint for linting the typescript. Is that something that would interest you? I could make that happen. But a fair warning - the PR would involve lots of code changes and I would recommend you to test all functionality afterwards.

If you are interested we also need to discuss the formatting rules. 
For example: 
```
{
  "tabWidth": 2,
  "printWidth": 80,
  "trailingComma": "none",
  "arrowParens": "avoid"
}
```

**Comment by florez-alberto** [comment]
You can clone the repo and test it directly on GitHub. The only rule is that it must compile without warnings to pass the vercel check. If it does and there is no malicious code we can approve it for prod.
